import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { cookies } from "next/headers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider, useAuth } from "~/context/AuthContext";
import NavBar from "~/components/ui/NavBar";
import { getServerAuthSession } from "~/lib/auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const authData = await getServerAuthSession();


  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <AuthProvider initialAuthState={authData}>
          <NavBar />
          {children}
          <ToastContainer position="top-center" autoClose={3000} />
        </AuthProvider>
      </body>
    </html>
  );
}